'use strict';
const fs=require('node:fs');const path=require('node:path');const {execFileSync}=require('node:child_process');const assert=require('node:assert/strict');const root=path.resolve(__dirname,'..');execFileSync(process.execPath,['scripts/build-static.js'],{cwd:root,stdio:'inherit'});const dist=path.join(root,'dist');
for(const file of ['index.html','404.html','manifest.json','service-worker.js','build-info.json','css/styles.css','css/base.css','css/features.css','css/theme.css','css/form-designer.css','css/coca-cola-ui.css','css/attention.css','css/attention-audio.css','js/core.js','js/db.js','js/app-base.js','js/app-utils.js','js/app-shell.js','js/app-sw-refresh.js','js/app-dashboard.js','js/app-form-view.js','js/app-form-designer.js','js/app-form-logic.js','js/app-form-save.js','js/app-records.js','js/app-record-detail.js','js/app-record-archive.js','js/app-directories.js','js/app-routing-views.js','js/app-activity-productivity.js','js/app-statistics.js','js/app-settings.js','js/app-notifications.js','js/app-attention-audio.js','js/app-backup.js','js/app-profile-help.js','js/app-demo.js','js/app.js','assets/app-icon.svg'])assert.equal(fs.existsSync(path.join(dist,file)),true,`Build sem recurso obrigatório: ${file}`);
for(const forbidden of ['docs','data','tests','scripts','js/equipment','assets/equipment','css/equipment-v5.css','js/app-equipment-catalog.js','js/app-equipment-manual.js','js/equipment-data.js'])assert.equal(fs.existsSync(path.join(dist,forbidden)),false,`Build publicou conteúdo não-runtime: ${forbidden}`);
const index=fs.readFileSync(path.join(dist,'index.html'),'utf8');assert.match(index,/V6\.3\.0 · attention audio/);assert.equal(/localhost|127\.0\.0\.1/.test(index),false);assert.match(index,/href="css\/form-designer\.css"/);assert.match(index,/href="css\/coca-cola-ui\.css"/);assert.match(index,/href="css\/attention\.css"/);assert.match(index,/href="css\/attention-audio\.css"/);assert.match(index,/src="js\/app-form-designer\.js"/);assert.match(index,/src="js\/app-statistics\.js"/);assert.match(index,/src="js\/app-notifications\.js"/);assert.match(index,/src="js\/app-attention-audio\.js"/);assert.equal(/js\/equipment\//.test(index),false);
const sw=fs.readFileSync(path.join(dist,'service-worker.js'),'utf8');assert.match(sw,/formularios-operacionais-v6\.3\.0/);assert.ok(sw.includes('./js/app-statistics.js'));assert.ok(sw.includes('./js/app-notifications.js'));assert.ok(sw.includes('./js/app-attention-audio.js'));assert.ok(sw.includes('./css/attention.css'));assert.ok(sw.includes('./css/attention-audio.css'));assert.equal(/js\/equipment\//.test(sw),false);
const buildScript=fs.readFileSync(path.join(root,'scripts/build-static.js'),'utf8');assert.equal(/photoRegistry|assets\\\/equipment\\\/photos/.test(buildScript),false);
const info=JSON.parse(fs.readFileSync(path.join(dist,'build-info.json'),'utf8'));assert.equal(info.build,'forms-designer-v6');assert.ok(info.runtimeFiles.includes('js/app-form-designer.js'));assert.ok(info.runtimeFiles.includes('js/app-statistics.js'));assert.ok(info.runtimeFiles.includes('js/app-notifications.js'));assert.ok(info.runtimeFiles.includes('js/app-attention-audio.js'));assert.ok(info.runtimeFiles.includes('css/coca-cola-ui.css'));assert.ok(info.runtimeFiles.includes('css/attention.css'));assert.ok(info.runtimeFiles.includes('css/attention-audio.css'));assert.equal(info.runtimeFiles.some(file=>/equipment-v5|js\/equipment/.test(file)),false);assert.equal(info.runtimeFiles.some(file=>/^(?:docs|data|tests|scripts)\//.test(file)),false);
console.log('Static GitHub Pages build V6.3.0: OK');
